### ISSUE TITLE
getopt quietly chops decimal places for integers

### ISSUE THREAD

**Issue by romanzenka** [trevorld/getopt#7]
I am trying to write software that would notify the user when they enter incorrect input.
The following code passes without raising any flags:

    spec <- matrix(c('number', 'n', 1, "integer"), byrow=TRUE, ncol=4)
    getopt(spec = spec, opt = c("--number", "1.234")) # The number is quietly rounded

Worse yet, if I enter gibberish, getopt simply warns and keeps going

    spec <- matrix(c('number', 'n', 1, "integer"), byrow=TRUE, ncol=4)
    getopt(spec = spec, opt = c("--number", "hello world")) # Warns, returns NA for the number

According to the robustness principle, this is probably justified. 
However, I would like to be able to override this behavior and have the function fail. I want warn the user that they did something wrong. If you cannot bake this in, a switch enabling this would be helpful.

**Comment by romanzenka** [comment]
Adding this code inside "consuming argument" branch helped:

          if(regexpr("^[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?$", peek.optstring) < 0 && spec[current.flag, col.mode] == "double") {
            stop(paste("flag \"", this.flag, "\" has to be a real number, got \"", peek.optstring, "\"",
                       sep = ""))
          }
          if(regexpr("^[-+]?[0123456789]+$", peek.optstring) < 0 && spec[current.flag, col.mode] == "integer") {
            stop(paste("flag \"", this.flag, "\" has to be an integer, got \"", peek.optstring, "\"",
                       sep = ""))
          }

Also, I noticed that your regex for the "double" type cannot deal with exponents. I would tweak the regex to the one I am using, which allows for the exponents to be specified.

**Comment by trevorld** [comment]
> I noticed that your regex for the "double" type cannot deal with exponents

I don't understand your point, exponential notation seems to work fine:

     > spec <- matrix(c('number', 'n', 1, "double"), byrow=TRUE, ncol=4) # or numeric
    > getopt(spec = spec, opt = c("--number=-1.2e-5"))$number
    [1] -1.2e-05
    > getopt(spec = spec, opt = c("--number=2E5"))$number
    [1] 2e+05

I think the user having the mental model that whatever they put in will be a string which will be cast to another data type using one of R's builtin functions to be the most simple (and robust) model.
 
The NA issue is easy to manually check (and throw an error if you desire)

    opt = getopt(spec)
    if (any(is.na(opt))) { stop("improper input resulted in NA's") }

Not persuaded if the double to integer check should be implemented in getopt.  What if they pass in 20.00?  What if they pass in 20.0000000000000002?  There are use cases where it would be desirable to round a double input upon casting to an integer (otherwise R's authors would have chosen to return NA's in such cases).

It would still be possible to directly test this by grabbing the number from the argument input albeit a bit of a hassle.

**Comment by romanzenka** [comment]
This was my rationale:

If the program expects an integer, and user specifies “hello world”, I would expect an error message saying “integer expected, got hello world”.
I cannot implement this functionality by checking for NA.
The best I can say is “something went wrong with parameter XYZ, but I am not sure what”.
I can live without this extra nice error message, so if you do not see its utility, fine with me.

However, there is a genuine bug with the double recognizing regex.

Try this:

spec <- matrix(c('number', 'n', 1, "double"), byrow=TRUE, ncol=4)
getopt(spec = spec, opt = c("--number","1.2e-5"))$number
[1] 1.2e-05

spec <- matrix(c('number', 'n', 1, "double"), byrow=TRUE, ncol=4)
getopt(spec = spec, opt = c("--number","-1.2e-5"))$number
Error in getopt(spec = spec, opt = c("--number", "-1.2e-5")) :
  long flag "number","-1.2e-5" is invalid

This behavior is surprising.

This can be easily fixed by changing the double-recognizing regex to:

"^-[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?$"

Thank you for your help!

--Roman

**Comment by trevorld** [comment]
I've incorporated the double regular expression suggestion and improved warning suggestion if the package tries to coerce a non-numeric string to a number.  I think I won't change behaviour with respect to doubles being coerced (i.e. rounded) to integers since this matches the behaviour of R's `storage.mode`.    

    > library('getopt')
    > spec <- matrix(c('number', 'n', 1, "double"), byrow=TRUE, ncol=4)
    > getopt(spec = spec, opt = c("--number","-1.2e-5"))$number
    [1] -1.2e-05
    > getopt(spec = spec, opt = c("--number","hello world"))$number
    Warning in value[[3L]](cond) : double expected, got “hello world”
    [1] "hello world"

**Comment by romanzenka** [comment]
This is beautiful! Thank you very much!
